---
title: Promise
date: 2022-07-23
categories: [前端]
tags: [js, 手写系列]
---

## 同步回调与异步回调

同步回调函数：在执行栈中执行，不会放入到事件队列中。比如：数组遍历相送的回调函数等

异步回调函数：不会立即执行，会放入事件队列中以后再执行。比如：定时器回调、ajax 回调、Promise 成功或失败的回调等

## Promise

Promise 是 JS 中异步编程的新方案，从语法上来说，Promise 是一个内置的构造函数，从功能上来说，Promise 的实例对象可以用来封装一个异步操作，并可以获取其成功或失败的值

一个 Promise 必然处于以下几种状态之一：

- 待定（pending）：初始状态，既没有被兑现，也没有被拒绝
- 已兑现（fulfilled）：意味着操作成功完成
- 已拒绝（rejected）：意味着操作失败

每一个 Promise 实例在刚被 new 出来的那一刻，状态都是 pending

new Promise 的时候，要传入一个回调函数，它是同步的回调，会立即在执行栈中执行，它被称为 executor，在 executor 中启动异步任务，如：ajax 请求、定时器等。

executor 函数接收 2 个参数，它们都是函数，分别用形参 resolve、reject 接收。

根据异步任务的结果做不同处理，如果异步任务成功了调用 resolve 函数会让 Promise 实例状态变为 fulfilled，同时指定成功的 value；如果异步任务失败了调用 reject 函数会让 Promise 实例状态变为 rejected，同时指定失败的 reason

Promise 的优势：

1. 指定回调函数的方式更加灵活，比如 setTimeout 必须在启动异步任务前指定回调函数，promise：启动异步任务=>返回 promise 对象=>给 promise 对象绑定回调函数（甚至可以在异步任务结束后指定）
2. 支持链式调用，可以解决回调地狱问题，但不是最优的解决回调地狱方案，最优解决方案`async/await`（底层实际上依然使用 then 的链式调用）

### Promise.prototype.then

通过 then 方法为 Promise 的实例指定成功、失败的回调函数，用来获取成功的 value、失败的 reason。then 方法所指定的成功的回调、失败的回调，都是异步的回调

```js
const p = new Promise((resolve, reject) => {
  console.log('new Promise执行了') // 第1打印

  setTimeout(() => {
    resolve(100)
    // reject(-100)
  }, 2000)
})

p.then(
  value => console.log(value), // 成功的异步回调
  reason => console.log(reason) // 失败的异步回调
)

console.log('first') // 第2打印
```

若一个 Promise 实例指定多个成功/失败的回调函数，则都会调用

```js
const p = new Promise((resolve, reject) => {
  console.log('new Promise执行了') // 第1打印
  setTimeout(() => {
    resolve(100)
  }, 2000)
})

p.then(
  value => console.log('@1', value), // 成功的异步回调
  reason => console.log('@1', reason) // 失败的异步回调
)
p.then(
  value => console.log('@2', value), // 成功的异步回调
  reason => console.log('@2', reason) // 失败的异步回调
)

console.log('first') // 第2打印
```

then 方法会返回一个新的 Promise 实例对象

```js
const p = new Promise((resolve, reject) => {
  console.log('new Promise执行了')
  setTimeout(() => {
    resolve(100)
  }, 2000)
})

const x = p.then(
  value => console.log('@1', value), // 成功的异步回调
  reason => console.log('@1', reason) // 失败的异步回调
)

console.log('first')
console.log(x) // Promise {<pending>}
```

then 方法返回的新的 Promise 实例的值和状态由 then 方法所指定的回调函数执行的结果决定

1. 如果 then 所指定的回调返回的是非 Promise 值`'a'`，那么新 Promise 实例状态为：fulfilled，成功的值为 value 为 a
2. 如果 then 所指定的回调返回的是一个 Promise 实例`p`，那么新 Promise 实例的状态值都与 p 一致
3. 如果 then 所指定的回调抛出异常，那么新 Promise 实例状态为 rejected，reason 为抛出的那个异常

```js
const p1 = new Promise((resolve, reject) => {
  resolve(100)
})

p1.then(
  value => {
    console.log('success1', value)
    return 'a'
  },
  reason => console.log('fail1', reason)
).then(
  value => {
    console.log('success2', value)
  },
  reason => console.log('fail2', reason)
)
```

### Promise.prototype.catch

catch 方法是 then 方法的语法糖，相当于：`then(null,onRejected)`

promise 的错误穿透：当使用 promise 的 then 链式调用时，可以在最后用 catch 指定一个失败的回调，前面任何操作出了错误，都会传到最后失败的回调中处理

如果不存在 then 的链式调用，就不需要考虑 then 的错误穿透

### Promise.prototype.finally

finally 方法返回一个 Promise。在 promise 结束时，无论结果是 fulfilled 或者是 rejected，都会执行指定的回调函数

### Promise.resolve

用于快速返回一个状态为 fufilled 或 rejected 的 Promise 的实例对象

```js
const p0 = Promise.reject(-100)
const p = Promise.resolve(p0)
p.then(
  value => console.log('success', value),
  reason => console.log('faile', reason) // 'faile' -100
)
```

### Promise.reject

用于快速返回一个状态为 rejected 的 Promise 的实例对象

### Promise.all

`Promise.all`方法接收一个参数为 n 个 Promise 实例的数组，返回一个新的 Pomise 实例，只有所有的 promise 都成功才成功，只要有一个失败就直接失败

### Promise.any

`Promise.any`接收一个 Promise 可迭代对象，只要其中的一个 promise 成功，就返回那个已经成功的 promise 。

如果可迭代对象中没有一个 promise 成功（即所有的 promises 都失败/拒绝），就返回一个失败的 promise 和 AggregateError 类型的实例，它是 Error 的一个子类，用于把单一的错误集合在一起。本质上，这个方法和 Promise.all() 是相反的。

### Promise.allSettled

`Promise.allSettled`方法返回一个在所有给定的 promise 都已经 fulfilled 或 rejected 后的 promise，并带有一个对象数组，每个对象表示对应的 promise 结果

```js
const p1 = Promise.resolve('a')
const p2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject('b')
  }, 500)
})
const p3 = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject('c')
  }, 2000)
})

Promise.allSettled([p1, p2, p3]).then(
  value => console.log('success', value),
  reason => console.log('fail', reason)
)
```

### Promise.race

`Promise.race`方法接收一个参数为 n 个 Promise 实例的数组，返回一个新的 Promise 实例，以最先出结果的 promise 为准

```js
const p1 = Promise.resolve('a')
const p2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject('b')
  }, 500)
})
const p3 = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject('c')
  }, 2000)
})

Promise.race([p1, p2, p3]).then(
  value => console.log('success', value),
  reason => console.log('fail', reason)
)
```

## 手写 Promise

### 规范

参考[promiseA+规范](https://promisesaplus.com/)

### 结构设计

- promise 初始状态为：pending
- promise 执行完 resolve 时状态为：fufilled
- promise 执行完 reject 时状态为：rejected

```js
class MyPromise {
  constructor(executor) {
    this.status = 'pending'
    this.value = undefined
    this.reason = undefined

    const resolve = value => {
      if (this.status === 'pending') {
        this.status = 'fufilled'
        this.value = value
      }
    }
    const reject = reason => {
      if (this.status === 'pending') {
        this.status = 'rejected'
        this.reason = reason
      }
    }

    executor(resolve, reject)
  }
}
const p = new MyPromise((resolve, reject) => {
  reject(-100)
  resolve(123)
})
console.log(p)
```

### then 方法的实现

```js
class MyPromise {
  constructor(executor) {
    this.status = 'pending'
    this.value = undefined
    this.reason = undefined

    const resolve = value => {
      if (this.status === 'pending') {
        this.status = 'fufilled'

        queueMicrotask(() => {
          this.value = value
          this.onFufilled(this.value)
        })
      }
    }
    const reject = reason => {
      if (this.status === 'pending') {
        this.status = 'rejected'

        queueMicrotask(() => {
          this.reason = reason
          this.onRejected(this.reason)
        })
      }
    }

    executor(resolve, reject)
  }

  then(onFufilled, onRejected) {
    this.onFufilled = onFufilled
    this.onRejected = onRejected
  }
}
const p = new MyPromise((resolve, reject) => {
  reject(-100)
  resolve(123)
})

p.then(
  value => console.log('success', value),
  reason => console.log('fail', reason)
)
```

#### 解决 then 方法多次调用被覆盖的问题

```js
class MyPromise {
  constructor(executor) {
    this.status = 'pending'
    this.value = undefined
    this.reason = undefined
    this.onFufilledFns = []
    this.onRejectedFns = []

    const resolve = value => {
      if (this.status === 'pending') {
        this.status = 'fufilled'

        queueMicrotask(() => {
          this.value = value
          this.onFufilledFns.forEach(fn => fn(this.value))
        })
      }
    }
    const reject = reason => {
      if (this.status === 'pending') {
        this.status = 'rejected'

        queueMicrotask(() => {
          this.reason = reason
          this.onRejectedFns.forEach(fn => fn(this.reason))
        })
      }
    }

    executor(resolve, reject)
  }

  then(onFufilled, onRejected) {
    this.onFufilledFns.push(onFufilled)
    this.onRejectedFns.push(onRejected)
  }
}

const p = new MyPromise((resolve, reject) => {
  resolve(123)
  reject(-100)
})

p.then(
  value => console.log('success1', value),
  reason => console.log('fail1', reason)
)

p.then(
  value => console.log('success2', value),
  reason => console.log('fail2', reason)
)
```

#### 解决 Promise 状态确定后再次调用 then 的问题

先看原生 promise 确定状态后再次调用 then 的情况

```js
const p = new Promise((resolve, reject) => {
  reject(-100)
  resolve(123)
})

p.then(
  value => console.log('success1', value),
  reason => console.log('fail1', reason)
)

p.then(
  value => console.log('success2', value),
  reason => console.log('fail2', reason)
)

setTimeout(() => {
  p.then(
    value => console.log('success3', value),
    reason => console.log('fail3', reason)
  )
}, 2000)
```

当使用 MyPromise 时，发现在 setTimeout 中使用 then 方法未被执行，这是因为 setTimeout 中的 onFufilled 与 onRejected 函数未被添加到`this.onFufilledFns`与`this.onRejectedFns`中

```js
class MyPromise {
  constructor(executor) {
    this.status = 'pending'
    this.value = undefined
    this.reason = undefined
    this.onFufilledFns = []
    this.onRejectedFns = []

    const resolve = value => {
      if (this.status === 'pending') {
        queueMicrotask(() => {
          if (this.status !== 'pending') return

          this.status = 'fufilled'
          this.value = value
          this.onFufilledFns.forEach(fn => fn(this.value))
        })
      }
    }
    const reject = reason => {
      if (this.status === 'pending') {
        queueMicrotask(() => {
          if (this.status !== 'pending') return

          this.status = 'rejected'
          this.reason = reason
          this.onRejectedFns.forEach(fn => fn(this.reason))
        })
      }
    }

    executor(resolve, reject)
  }

  then(onFufilled, onRejected) {
    if (this.status === 'fufilled' && onFufilled) {
      onFufilled(this.value)
    }

    if (this.status === 'rejected' && onRejected) {
      onRejected(this.reason)
    }

    if (this.status === 'pending') {
      this.onFufilledFns.push(onFufilled)
      this.onRejectedFns.push(onRejected)
    }
  }
}

const p = new MyPromise((resolve, reject) => {
  reject(-100)
  resolve(123)
})
console.log(p)
p.then(
  value => console.log('success1', value),
  reason => console.log('fail1', reason)
)

p.then(
  value => console.log('success2', value),
  reason => console.log('fail2', reason)
)

setTimeout(() => {
  p.then(
    value => console.log('success3', value),
    reason => console.log('fail3', reason)
  )
}, 2000)
```

#### then 方法的链式调用

```js
function execFnCatchError(fn, value, resolve, reject) {
  try {
    const result = fn(value)
    resolve(result)
  } catch (error) {
    reject(error)
  }
}

class MyPromise {
  constructor(executor) {
    this.status = 'pending'
    this.value = undefined
    this.reason = undefined
    this.onFufilledFns = []
    this.onRejectedFns = []

    const resolve = value => {
      if (this.status === 'pending') {
        queueMicrotask(() => {
          if (this.status !== 'pending') return

          this.status = 'fufilled'
          this.value = value
          this.onFufilledFns.forEach(fn => fn(this.value))
        })
      }
    }
    const reject = reason => {
      if (this.status === 'pending') {
        queueMicrotask(() => {
          if (this.status !== 'pending') return

          this.status = 'rejected'
          this.reason = reason
          this.onRejectedFns.forEach(fn => fn(this.reason))
        })
      }
    }

    executor(resolve, reject)
  }

  then(onFufilled, onRejected) {
    return new MyPromise((resolve, reject) => {
      if (this.status === 'fufilled' && onFufilled) {
        execFnCatchError(onFufilled, this.value, resolve, reject)
      }

      if (this.status === 'rejected' && onRejected) {
        execFnCatchError(onRejected, this.reason, resolve, reject)
      }

      if (this.status === 'pending') {
        this.onFufilledFns.push(() => {
          execFnCatchError(onFufilled, this.value, resolve, reject)
        })
        this.onRejectedFns.push(() => {
          execFnCatchError(onRejected, this.reason, resolve, reject)
        })
      }
    })
  }
}

const p = new MyPromise((resolve, reject) => {
  resolve(123)
  reject(-100)
})
console.log(p)
p.then(
  value => {
    console.log('success1', value)
    return 'success~~~~~'
  },
  reason => {
    console.log('fail1', reason)
    return 123
  }
).then(
  value => console.log('success then', value),
  reason => console.log('fail then', reason)
)

p.then(
  value => console.log('success2', value),
  reason => console.log('fail2', reason)
)

setTimeout(() => {
  p.then(
    value => console.log('success3', value),
    reason => console.log('fail3', reason)
  )
}, 2000)
```
